# Generated by Django 3.2.8 on 2021-11-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToMeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persone', models.CharField(max_length=32)),
                ('phone_number', models.IntegerField()),
                ('date_meeting', models.DateField()),
                ('is_done', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='dateCreated',
            new_name='date_created',
        ),
    ]
