# Generated by Django 3.2.8 on 2021-11-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211109_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100)),
                ('goal_description', models.CharField(max_length=200)),
                ('month', models.DateField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('NORMAL', 'Normal'), ('HARD', 'Hard')], default='NORMAL', max_length=6)),
            ],
        ),
    ]
