# Generated by Django 3.2.8 on 2021-11-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_todo_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done_today', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('habit_description', models.TextField(max_length=200)),
            ],
        ),
    ]
